replicaCount: 5
image:
  pullPolicy: IfNotPresent
  repository: public.ecr.aws/h3o4k0u5/argoeks
  version: latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name:
podSecurityContext: {}
securityContext: {}
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: k8s-default-myingres-60c851a24e-782417590.ap-south-1.elb.amazonaws.com
      paths: []
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}